### ISSUE TITLE
Jest mocking does not work in files using import syntax

### ISSUE THREAD

**Issue by mknet** [standard-things/esm#131]
_Jest_ offers the feature to mock functions (and objects). Jest also supports the mocks for the "code under test" importing dependencies via require.
It seems like this support is broken while using ESM.

I created [a small repo](https://github.com/mknet/esm-jest-import-issue) to get an idea of what I mean.

**Comment by jdalton** [comment]
Thank you for the heads up @mknet!

I think this may fall more on Jest's side. After digging into it a bit it looks like they replace `require` with their own and its own `require.cache` which is not the built-in cache of `require.cache === require("module")._cache`. Since it's using it's own cache it's mocks are not seen by others that reference the built-in cache.
