### ISSUE TITLE
async generators bug

### ISSUE THREAD

**Issue by neyasov** [standard-things/esm#135]
`scripts/node9-test.js`
```
async function* generator() {
  yield 42;
}
```

`node --harmony scripts/node9-test.js `

`node --harmony -r @std/esm scripts/node9-test.js`
```
async function* generator() {
              ^

SyntaxError: Unexpected token
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

**Comment by jdalton** [comment]
Hi @neyasov!

`@std/esm` parses files as such support for various syntax is needed to be in place. The `--harmony` flag is known to be buggy in Node so I don't tend to support it in my projects. Our parser, [acorn](https://github.com/ternjs/acorn), adopts syntax when it has reached at least stage 4. The [async iteration](https://github.com/tc39/proposal-async-iteration) proposal is stage 3 *(so super close)*. I normally wait until acorn or Node lands support for async iteration unflagged before I start looking into a solution. However, since we just need basic parsing support things look to be much easier. I'll kick this around and see if I can come up with a patch.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/41b4fcb4976214c26ff30998afc98e087567deae; Tests https://github.com/standard-things/esm/commit/95ada4459ba5f5234ce8f317847c1b4714808764.
