### ISSUE TITLE
Module alias is not working

### ISSUE THREAD

**Issue by ChuntheQhai** [standard-things/esm#154]
I got "Cannot find module" with my @lib on import. Is there way to fix this?

**Package.json**
```
{...
"scripts": {
    "dev": "DB_HOST=localhost:27017 nodemon --trace-warnings -w src --exec \"node src/index.js\"",
    "start": "node src/index.js",
    "test": "eslint src"
  },
  "@std/esm": "cjs",
  "_moduleAliases": {
    "@root": "./src",
    "@api": "./src/api",
    "@lib": "./src/lib",
    "@middleware": "./src/middleware",
    "@models": "./src/models"
  }
...}
```

**Index.js**
```
require = require('@std/esm')(module)
module.exports = require('./app.mjs')
```

**app.mjs**
```
require('module-alias/register');
import http from 'http';
...
```

**Comment by jdalton** [comment]
Hi @ChuntheQhai!

Can you create a simple repro repo for me to look at?

**Comment by ChuntheQhai** [comment]
@jdalton 

Here's my repo for ESM with module alias:
https://github.com/ChuntheQhai/simple-esm-module-alias

**Comment by jdalton** [comment]
Okay @ChuntheQhai!

Making this work is doable. I'm going to make it work with the option `"@std/esm": "cjs"`. The reason it doesn't work at the moment is because of two things. The first is that `module-alias` assumes the module system is referencing `Module._nodeModulePaths` and `Module._resolveFilename`. The second is that it assumes `Module` is of `require("module")`. So for my part when `"@std/esm":"cjs"` I'll reference `Module` methods directly instead of cherry-picked imports of them. For the other I'll make a PR to `module-alias` so that it doesn't use `require("module")` directly and will get it from the `module.constructor`. This way it will work with our module system *(and others)*.

**Comment by kenotron** [comment]
@ChuntheQhai / @jdalton  - did this ever address the issue? I'm trying to make jest work with esm in my setup and it seems having module alias would solve another one of the problems (the last problem would be all those .css / .scss imports)...

**Comment by kenotron** [comment]
Okay, I updated to latest @std/esm and it WORKS. It seems that the latest esm versions has regressed this behavior...

**Comment by jdalton** [comment]
> did this ever address the issue

Yes. 

> It seems that the latest esm versions has regressed this behavior...

Yep. I was just going to post that. It looks like I regressed it when I tried to cache a bit more across loader instances. I'll fix that up tonight.

**Comment by kenotron** [comment]
Okay I see this is fixed for cjs 👍 

However, I'm trying to update that simple repo from @ChuntheQhai with the latest esm, but it wouldn't work since the `app.mjs` is importing it as esm... wondering how I can get the same behavior as `@std/esm`'s setting for `package.json` specifying `"esm": "cjs"` - I tried `{mode: 'auto', cjs: true}` but didn't work.

**Comment by jdalton** [comment]
`.mjs` is locked down on purpose. Since it's the Node way (tm) and they haven't fully written its support yet we can't responsibly expand its functionality. You'll not be able to enable it with `.mjs`. For things to "just work" you'll want to stick with `.js` for now.

**Comment by jdalton** [comment]
That's esm with `.js`.

**Comment by kenotron** [comment]
I wanted to follow up on this - I've forked the simple repro and made it work:
https://github.com/kenotron/simple-esm-module-alias

**Comment by outception** [comment]
dsfgdzxfxzdf

**Comment by outception** [comment]
Such a common usage, and zero explanation in the document.

**Comment by outception** [comment]
const esmRequire = require('esm')(module, { cjs: { topLevelReturn: true }})

`esmRequire('module-alias/register')`

require('module-alias').addAliases({
    '@': __dirname
})

esmRequire('./logic/demo')

**Comment by andersondanilo** [comment]
For me that worked

Added "@std/esm": "cjs" to package.json
nodemon -r @std/esm -r module-alias/register ./app/server.mjs

**Comment by yukihirop** [comment]
If you want to use [addAliases in module-alias](https://github.com/ilearnio/module-alias#advanced-usage),  you can do this.
https://github.com/yukihirop/simple-esm-module-alias

**Comment by fancymo** [comment]
> const esmRequire = require('esm')(module, { cjs: { topLevelReturn: true }})
> 
> `esmRequire('module-alias/register')`
> 
> require('module-alias').addAliases({
> '@': __dirname
> })
> 
> esmRequire('./logic/demo')

with run esmRequire('module-alias/register')
It's wrong ：Cannot find module 'module-alias/register'

**Comment by TheDirigible** [comment]
This problem has been plaguing me for years because I want to write good quality code that is shared between node & browser.
I finally found a system that works:
 * Place 'nesm.js' in the root of your project
 * [optional] Place the 'nesm' shell script in your path, make it executable
 * Run scripts with: '**nesm file_to_run.js**' or '**node path/to/nesm.js -- file_to_run.js**'

**'nesm.js'**

    /*
     * esm and module-alias do not play nicely together.
     * this precise arrangement is the only way I found to make it work.
     * you can run this from anywhere in your project hierarchy.
     * you can use args, and use in npm scripts.
     * encourage the node.js devs to make this work natively.  ux matters.
     * ---- CAVEATS
     * will not work with "type":"module"
     * ---- SETUP
     * place 'nesm.js' in the root of your project
     * [optional] place the 'nesm' shell script in your path, make it executable
     * ---- USAGE
     * > nesm file_to_run.js
     * to run without the nesm shell script:
     * > node path/to/nesm.js -- file_to_run.js
     * to run with nodemon:
     * > nodemon -- path/to/nesm.js -- file_to_run.js
    */
    require = require('esm')(module);   // eslint-disable-line no-global-assign
    require('module-alias/register');   // must come after esm for some reason
    
    let runNext;
    for(const arg of process.argv) {
        if(runNext) {
            let filename = arg;
            if(filename[0]!='.' && filename[0]!='/') filename = './'+filename;
            require(filename);
            break;
        }
        runNext = (arg=='--');
    }

**'nesm' shell script**

    #!/bin/bash
    if [ -z $1 ]; then
        echo "Node esm runner.  Usage: nesm file_to_run.js"
        exit 1
    fi
    baseDir=$( pwd )
    while [ ! -f "$baseDir/nesm.js" ]; do
        if [ ${#baseDir} -le 1 ]; then
            echo "nesm.js not found in folder ancestry"
            exit 1
        fi
        baseDir="$(dirname "$baseDir")"
    done
    file1=$(realpath $1);
    node $baseDir/nesm.js -- $file1
