### ISSUE TITLE
Regression from 0.17.0

### ISSUE THREAD

**Issue by JLHwung** [standard-things/esm#164]
I use esm to bundle my library, after upgrading to 0.17.0 the jest unit test is broken. It is also broken in 0.17.1.

You can replicate the broken test on https://github.com/JLHwung/postcss-font-family-system-ui/pull/28, [CI Result](https://travis-ci.org/JLHwung/postcss-font-family-system-ui/builds/306099190).

The test is okay for @std/esm<=0.16.0. [CI Result](https://travis-ci.org/JLHwung/postcss-font-family-system-ui/builds/304599523).

Edit: updated negative CI result link.

**Comment by jdalton** [comment]
Thanks @JLHwung,

I'll look into it!

**Comment by jdalton** [comment]
I've found the issue! With 0.17.0 we pass more files through our loader. So since you're configured to `"esm":"all"` the third-party cjs-files are being treated like ESM and erroring out. If I switch the esm mode to `"esm":"js"` then it uncovers another issue with how Jest is mocking out its `require.extensions` *(jest is making it an empty object)*. The `require.extensions` object is used by `Module` internals to resolve extensionless module paths like `"./declaration"`.

I can make the "all" mode apply to just first-party code and also detect more of Jest bogus mocks to avoid the error.

**Comment by JLHwung** [comment]
I tried switching to `esm: js` and found `can not find "./declaration"` error but I forget to mention that. 😄 

Jest is not the first time breaking the loader, how about we add some smoking test for the integration with jest? Or other popular framework.

**Comment by jdalton** [comment]
Patched `require.extensions` use https://github.com/standard-things/esm/commit/07c1681b84e1955ca88e11dbf90994ce29c2e1bd.
