### ISSUE TITLE
Circular dependency doesn't work with anonymous function declaration

### ISSUE THREAD

**Issue by nicolo-ribaudo** [standard-things/esm#183]
https://github.com/nicolo-ribaudo/std-esm-bug-anonymous-fn-decl

It works with node, but not with `@std/esm`:

```
~/Documenti/anonymous-function-declaration on  master is 📦  v1.0.0 via ⬢ v8.9.2 took 23s 
•100% ➜ node --experimental-modules main.mjs 
(node:16566) ExperimentalWarning: The ESM module loader is experimental.
fn

~/Documenti/anonymous-function-declaration on  master is 📦  v1.0.0 via ⬢ v8.9.2 
•100% ➜ node -r @std/esm main.mjs
TypeError: f is not a function
    at /home/nicolo/Documenti/anonymous-function-declaration/g.mjs:2:9
    at Object.<anonymous> (file:///home/nicolo/Documenti/anonymous-function-declaration/file:/home/nicolo/Documenti/anonymous-function-declaration/file:/home/nicolo/Documenti/anonymous-function-declaration/g.mjs:1)
    at Module._compile (file:///home/nicolo/Documenti/anonymous-function-declaration/file:/home/nicolo/Documenti/anonymous-function-declaration/file:/home/nicolo/Documenti/anonymous-function-declaration/module.js:635:30)

```

If I give a name to the function defined in `f.js` or I remove the first import from `main.js`, it works as I'd expect.
I'm not 100% sure that this is a bug, since I don't understand well the part of the spec related to modules and rollup behaves exactly like `@std/esm`.

**Comment by jdalton** [comment]
Hi @nicolo-ribaudo!

Looks like I can fix this with a little import/export order juggling.
I'll kick something around and report back.

**Comment by jdalton** [comment]
For a temp workaround you can move the `g` import above `f`:
```js
import g from "./g";
import f from "./f";
```

**Comment by nicolo-ribaudo** [comment]
Thank you!

**Comment by benjamn** [comment]
Would you expect this to work for arbitrary `export default` expressions? For example:
```js
export default fnThatReturnsFn();
```
The `fnThatReturnsFn()` call could have side effects, so the JS runtime can't automatically hoist it.

In some sense,
```js
export default function () {...}
```
is just another `export default <expression>` form, so the `default` export arguably should not be defined until that expression has been evaluated (in statement order, without any special hoisting).

You can still import the `default` export before it has a value, just like `f` in this code:
```js
export let f;
import "./module/that/imports/and/immediately/uses/f.js";
// Too late!
f = function () {...};
```
Or even simpler:
```js
import "./module/that/imports/and/immediately/uses/f.js";
// Too late!
export let f = function () {...};
```
Since the expression in question isn't evaluated until after the circular import, there may not be anything the JS runtime can safely do to make this work for you.

**Comment by jdalton** [comment]
@benjamn 
> Would you expect this to work for arbitrary `export default` expressions? 

It's less about what I or @nicolo-ribaudo expects to work and more about what does work in the runtime. In this case his example does work with `--experimental-modules` so is something we should support.

**Comment by benjamn** [comment]
I agree we should reconcile what `@std/esm` does with what Node does.

However, I understand
```js
export default function () {}
```
to be exporting a function expression, which is not a declaration, so I'm not sure I get why it should be hoisted.

**Comment by nicolo-ribaudo** [comment]
It is an anonymous function declaration:

- https://tc39.github.io/ecma262/#prod-ExportDeclaration
  ```
  ExportDeclaration:
    ...
    export default HoistableDeclaration[~Yield, ~Await, +Default]
    ...
  ```
- https://tc39.github.io/ecma262/#prod-HoistableDeclaration
  ```
  HoistableDeclaration[Yield, Await, Default]:
    FunctionDeclaration[?Yield, ?Await, ?Default]
    ...
  ```
- https://tc39.github.io/ecma262/#prod-FunctionDeclaration
  ```
  FunctionDeclaration[Yield, Await, Default]:
    ...
    [+Default] function ( FormalParameters[~Yield, ~Await] ) { FunctionBody[~Yield, ~Await] }
  ```

Btw, I just realized that this issue needs to be fixed also or async functions and generators.

**Comment by jdalton** [comment]
@nicolo-ribaudo 
> EDIT: @jdalton If you haven't started working on this yet, I'd like to contribute!

That would be so awesome! The place to start looking is [here](https://github.com/standard-things/esm/blob/a9ba193c6613f5be09cd20c071a451317d8911bc/src/visitor/import-export.js#L114-L136).

**Comment by benjamn** [comment]
Ok, I didn't realize anonymous declarations were a thing!

By the way, I think you can get this to work in `@std/esm` without giving the function a name, as long as the Acorn parser gets the `.type` right (`FunctionDeclaration` rather than `FunctionExpression`). This is important because the function could be parenthesized, in which case it really should be a `FunctionExpression`. Since you can't easily tell if there were parentheses by looking at the AST, you can't just override the `.type` in this case, so you need to be able to trust the parser.

**Comment by nicolo-ribaudo** [comment]
@benjamn The name is needed because anynimous declarations are only allowed after `export default`, so they need an id when `export default` is removed.
I just checked and acorn generates the correct node types.

**Comment by jdalton** [comment]
Moved to #187.
