### ISSUE TITLE
Best practice for package publishing

### ISSUE THREAD

**Issue by vjpr** [standard-things/esm#321]
From https://github.com/dherman/defense-of-dot-js/issues/18#issuecomment-373945938:

@jdalton Quick questions on esm:

Is the idea with esm that I should publish packages using ES2015+ features and they will be transpiled on the fly by esm?

Is there any option to precompile with esm - or is that not the point?

Do I require esm in my published library, or do I instruct the user to require it?

babel-register should be required only once. Is esm the same, or does it handle this better than babel-register?

I will incur a startup compilation penalty when using esm?

If I use babel-register plugins, the user will still be forced to require babel-register when requiring my module - so my package will not work out of the box unless I precompile, correct?

Does esm handle package.json main fields like module?

Finally, if I still want to precompile (to be the fastest when using babel plugins), esm doesn't help me correct?

**Comment by jdalton** [comment]
Hi @vjpr!

> Is the idea with esm that I should publish packages using ES2015+ features and they will be transpiled on the fly by esm?

The `esm` loader just tackles ES module related syntax, so `import`, `export`, `import.meta`, etc.
Anything beyond that is up to your version of Node.

> Is there any option to precompile with esm - or is that not the point?

You don't have to worry about precompilation. Because `esm` is just concerned with ES module related syntax any source instrumentation is minimal and cached for subsequent use.

> Do I require esm in my published library, or do I instruct the user to require it?

You use `esm` as a dependency of your package. Your package consumers could be totally unaware that your package is written in ESM syntax.

> babel-register should be required only once. Is esm the same, or does it handle this better than babel-register?

`@babel/register` hooks into the global module system which is why it's not appropriate for production or published package use as a dependency. The `esm` loader is different and when used in packages via the following syntax it is completely isolated (so does not hook into the global module system).
```js
require = require("esm")(module)
module.exports = require("./main.js").default
```

> I will incur a startup compilation penalty when using esm?

There is a minor 1 time cost (a little over 1ms per module) but after that it's close to native speed. The `esm` loader even cached engine code cache so subsequent cjs loads will also be faster.

> If I use babel-register plugins, the user will still be forced to require babel-register when requiring my module - so my package will not work out of the box unless I precompile, correct?

`@babel/register` is a heavier, non-production, generic runtime transpiler. It's completely separate from the `esm` loader. If you are using `@babel/register` in your CLI tool or application you can combo them (disabling modules in Babel with `modules:false` and requiring them as `node -r esm -r @babel/register`.

> Does esm handle package.json main fields like module?

The `esm` loader doesn't recognize the `module` field because it's non-standard and means different things for different packages. With `esm` you don't have to ship dual packages and can just ship ESM as your primary source.

> Finally, if I still want to precompile (to be the fastest when using babel plugins), esm doesn't help me correct?

The `esm` loader isn't related to Babel but you can run Babel or TypeScript transpiled code through `esm` just fine.

**Comment by vjpr** [comment]
Thank you for the detailed response! I will dive in deeper to esm. It
sounds great.
