### ISSUE TITLE
top-level await in REPL?

### ISSUE THREAD

**Issue by wmertens** [standard-things/esm#336]
I tried this but that doesn't work:

```
$ ESM_OPTIONS={await:true} node -r esm
> await Promise.resolve(5)
await Promise.resolve(5)

SyntaxError: Unexpected identifier
```

would be awesome if that worked…

**Comment by jdalton** [comment]
Hi @wmertens!

Top-level `await` support is actually in master branch builds of Node. However, before it lands in Node v10 it will be [put behind the `--experimental-repl-await`  flag](https://git.io/vx0nM).

Top-level `await` requires [touching a fair bit of the REPL](https://github.com/nodejs/node/commit/eeab7bc0688256247c47099a90c67741e6637e42). One neat thing is that if you [compile `esm` into Node](https://github.com/standard-things/esm/wiki/Compile-Node) it will actually update and improve the WIP top-level `await`.

> [![tweet](https://user-images.githubusercontent.com/4303/38119545-69694bf2-3377-11e8-820c-46bdbbb52a50.gif)](https://twitter.com/jdalton/status/978883020814999552)

The reason compilation is required is at the moment without replacing large chunks of the REPL Node relies on its own outdated and insufficiently configured copy of the `acorn` parser. When `esm` is compiled into Node we can access and update the `acorn` reference to use our own improve copy.

The reason I bring up the compilation step is because I can see a future in which one may get a pre-built or modified Node with `nvm` or `nvs`.

**Comment by jdalton** [comment]
**Update:**

You may also dig that I recently got [an enhancement merged](https://github.com/babel/babel/pull/7637) into the Babel Babylon parser enabling top-level `await` support. This is important because it will enable linting of top-level `await` through [babel-eslint](https://github.com/babel/babel-eslint)!

**Comment by wmertens** [comment]
Oh wow, thank you for your detailed comment! ❤
I will check out the custom `node` approach.
