### ISSUE TITLE
Ability to support more than *.mjs

### ISSUE THREAD

**Issue by geelen** [standard-things/esm#34]
Was just trying out this loader to try out some mobx code, but their published ES6 module bundle is named `mobx.module.js`. I was wondering whether it was worth adding a config option to allow other extensions (like `*.module.js`) to be autodetected as an ESM? I've also left a PR there to rename it to `.mjs` going forward: https://github.com/mobxjs/mobx/pull/1131

FYI, trying to use `"esm": "all"` or `"esm": "js"` wasn't working for me either with the `node -r` usage. This is my [package.json](https://gist.github.com/geelen/869bb3de86ad4659b3e9c6b993a4770b), maybe I'm doing something wrong?

Love the idea behind this project though, great work!

**Comment by jdalton** [comment]
Hi @geelen!

The configs should work (that's their purpose). If the hook is enabled with -r then all other scripts loaded will pass through it (including .js) so as long as it can detect that your package has opt'ed in with `@std/esm` being a dep, dev dep, or peer dep, then it should be enabled. I noticed you only have a config option. I may expand our opt-in to detecting that as well (since it's pretty explicit).
