### ISSUE TITLE
repro for issue #366

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#369]
@jdalton just looked at https://github.com/standard-things/esm/issues/366 again.

repro:
https://github.com/dnalborczyk/esm-issue-366

versions are locked down.

```console
cd app1
npm i  # or better npm ci
npm start
```

it seems the existence of a package.json file has an effect on the outcome of the import, which I would have not expected either. I thought package.json would only be valued if one wants to import a package without a direct path but with a "main" entry specified.

some observations, which I'm not sure they are intended:
- it does not matter if app1 has a _higher or lower_ version of esm installed than app2 (fails nonetheless) 
- cache folder is being created for App2 (even if node_modules doesn't exists prior)

**Comment by jdalton** [comment]
> cache folder is being created for App2 (even if node_modules doesn't exists prior)

That's fine because it's telling App2 that it's cache (when it does run) is dirty.

> it does not matter if app1 has a higher or lower version of esm installed than app2 (fails nonetheless)

I cannot repro that. If I make App2 pin at `3.0.19` then the app works. This looks like the same root issue which is you're explicitly telling `esm` not to work there by pinning one app to an older version. If I change App2 from `3.0.16` to `^3.0.16` then App1 reaching into App2 will also work.

If App2 used `require("esm")(module)` to load and export its package then there is no issue either (regardless of App1 `esm` version).

I can handle this in a couple ways.

 * I can improve the error message to state the expected version and notify if the expected version is pinned _(no leading `^`, `~`, `>`, or `<`)_.

* I can remove the gate entirely. The `esm` gate was added way back in `@std/esm` when it was on the global hook by default and so it was super important to not step on other packages. However, since this is the local app scenario I could just say yolo to it and the leading loader wins. This means if the source you're trying to load expects a newer version _(with a feature not supported)_ things will just not work as expected.

**Comment by dnalborczyk** [comment]
> > it does not matter if app1 has a higher or lower version of esm installed than app2 (fails nonetheless)

> I cannot repro that.

sorry, I literally meant **higher** or **lower**, not **same** (should have emphasized)

what I'm lacking is the misunderstanding that the mere presence of a package.json file in another folder has an effect on how the file is being loaded with esm. though I have no knowledge on what node itself does (without using esm).

**Comment by dnalborczyk** [comment]
maybe my misunderstanding is also related to the intended usage for module packages.

e.g https://github.com/lodash/lodash/issues/3745  I suppose you'd make the lodash entry point for cjs consumers with esm. if someone wants to use the ESM modules of lodash v5, I suppose they would need to use esm -- for the time being -- unless you're going with *.mjs.

assuming someone would be referencing:

```javascript
import { pick } from "lodash"
// or
import pick from "lodash/pick"
```

why would esm [loaded from the root app] care about the esm module in dependencies which is only loaded (and meant) for the cjs consumers to create an entry point in lodash?

**Comment by jdalton** [comment]
You're a bit all over the place with this so I'll just brain dump how it is. The loader is mimicking how npm deps work. By pinning to a specific version you are stating only run that version. That said I can date to the classic semver `^` for local runs and as well as improve the error for the next major bump (v4). The `esm` loader already errors when it doesn't recognize a provided option so I don't have to worry about mystery fails on that front (though I could improve that message as well).

**Comment by dnalborczyk** [comment]
_btw, just to make sure, I'm not arguing for anything, just trying to understand._

yeah, I know how npm does semver (to a certain degree). but that's not so much the issue. I also don't know what action esm should take on matters of ^, ~, or *. I have no opinion on that. I haven't thought about it, since I don't understand why the version information is being taken into consideration in the first place :smiley:

what it comes down to is:
when I'm referencing a file from a folder, which happens to have a package.json file, with an entry for a dependency on esm (but nothing inside that folder has a reference to esm, as well as there's no node_modules folder inside), why is the esm version being taken into consideration for the app referencing a file from that folder?

Maybe it' some inner workings of esm I'm not aware of.

**Comment by jdalton** [comment]
[v3.0.20](https://github.com/standard-things/esm/releases/tag/3.0.20) is released :tada:
