### ISSUE TITLE
`arguments` is defined

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#37]
minor?

some `function` probably just needs to be changed to an arrow function somewhere...

```
// a.mjs
import assert from 'assert';
// top level test
let defined;
try {
  arguments;
  defined = true;
}
catch (e) {
  defined = false;
}
assert.strictEqual(defined, false);

// in arrow test
const test = () => {
  let defined;
  try {
    arguments;
    defined = true;
  }
  catch (e) {
    defined = false;
  }
  return defined;
}
assert.strictEqual(test(), false);
```

**Comment by bmeck** [comment]
add `new.target` in this bag too.

**Comment by jdalton** [comment]
Thanks @bmeck!

This is a known limitation. I've not found a way to get rid of the `arguments` object entirely while also having a `this` of `undefined` so I compromised with at least having an empty `arguments` object. I could do some more complex parse time checking but since it seems rather minor I'm OK punting it for now.

**Comment by jdalton** [comment]
If you have a way though, I'd be more than happy to review a pull request.

**Comment by jdalton** [comment]
Fixed catching `new.target` in https://github.com/standard-things/esm/commit/65cc9cf6c576035b8dd67bee8c49d48b9cc22809.
I'll be adding a round of unit tests over the next couple of days to solidify support.
