### ISSUE TITLE
Caching & interaction with nyc

### ISSUE THREAD

**Issue by novemberborn** [standard-things/esm#402]
I'm using `esm` programmatically. Caching is enabled.

I can run my tests fine without `nyc`. However if I do this first, and then run *with* `nyc`, no coverage is reported. If I delete `node_modules/.cache/esm` and try again I do get coverage results.

Does `esm` discard the instrumented code and load from its cache instead? What does it use as the cache key?

**Comment by jdalton** [comment]
Hi @novemberborn!

Could you create a repro repo for me to look at?

**Comment by novemberborn** [comment]
Yup, see https://github.com/novemberborn/__esm-402

**Comment by jdalton** [comment]
**Update:**

When running as `nyc npm test` there's no way to detect we're being run by `nyc` so the only safe option is to punt on caches when we detect an `nyc` cache folder.

**Comment by apparebit** [comment]
Hi @jdalton,

Does your fix work for monorepos? Collecting coverage via `nyc` when running under `esm` has been broken for me off and on for a while now. So last week I started to aggressively dig into their interaction and it became apparent that caching was to blame. My work-around was to simply nuke __all__ `node_modules/.cache` directories between runs. See [js-junction](https://github.com/apparebit/js-junction); though tests are currently broken 😢.

I emphasized "all" because whereas `nyc` appears to only rely on the eponymous subdirectory of `node_modules/.cache`, `esm` does create subdirectories for each package as well, i.e., under `packages/*/node_modules/.cache`.

**Comment by jdalton** [comment]
Hi @apparebit!

If you give me a repro step I can dig into it.

**Comment by jdalton** [comment]
I'm guessing we'll look at the current-working-directory `node_modules/nyc` but would need to a repro to confirm.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/dfa26a297b7a7095cb8dc9615e4b910fff6e6557.

**Comment by novemberborn** [comment]
> When running as nyc npm test there's no way to detect we're being run by nyc so the only safe option is to punt on caches when we detect an nyc cache folder.

nyc exposes some environment variables: https://github.com/istanbuljs/nyc/blob/bc9ffe59370da43daa62853992402d83c0d17dd4/bin/nyc.js#L44:L49

`NYC_CWD` or `NYC_ROOT_ID` seem like good ones to detect.

This seems preferable to the current approach, which will prevent caching once you've run `nyc` once in your development environment. Caching in nyc can also be disabled, or the caches stored in a different directory.

**Comment by jdalton** [comment]
With that I was able to simplify detection.

Patched https://github.com/standard-things/esm/commit/030f60af7594472d411e27e7c1cb5277bdb24511.

Now when running by way of `nyc` we check if we have an existing `.nyc` marker file in our cache. If we don't we ignore the cache and overwrite it. If we do see the `.nyc` marker then we know we can use the cache.

**Comment by jdalton** [comment]
**Update:**

[v3.0.35](https://github.com/standard-things/esm/releases/tag/3.0.35) is released :tada:
