### ISSUE TITLE
require.main is undefined

### ISSUE THREAD

**Issue by LeafHacker** [standard-things/esm#452]
`require.main.filename` throws `TypeError: Cannot read property 'filename' of undefined`. I can't get around this since the [statement](https://github.com/dirigeants/klasa/blob/189ae83b1861cd22599ffc5a9e604ce6fa1dc0e9/src/lib/Client.js#L138) is in a dependency of mine.

**Comment by jdalton** [comment]
Hi @LeafHacker!

Do you have a repro scenario? What is your settings?

**Comment by jdalton** [comment]
If your main file is `.mjs` it will not show up on the `require.main` and this is by design. You'll want to switch to `.js`.

**Comment by LeafHacker** [comment]
I can reproduce with the same [branch](https://github.com/ImpactDevelopment/ImpactBot/tree/esm) as linked in #450. No mjs code at all.

**Comment by jdalton** [comment]
Ah, after spending about 30 minutes poking around and adding a bunch of peer deps and compiling a bunch of stuff I still can't narrow down a fail case related to `require.main`. Could you provide additional instructions on how to reproduce the issue.

**Comment by jdalton** [comment]
Ah it's because the code in that branch [changed](https://github.com/dirigeants/klasa/blob/4ff2aba070da2a484145d93b35f90e4ccbc454ea/src/lib/Client.js#L146) to no longer use `require.main`. Even if I add it back and do a `console.log(require.main.filename)` I'm getting `/Users/jdalton/projects/ImpactBot/index.js`. If you can produce a simplified repro I'll totally dig into it.

**Comment by jdalton** [comment]
**Update:**

Oh, I noticed your esm branch has a [`.esmrc.json`](https://github.com/ImpactDevelopment/ImpactBot/blob/esm/.esmrc.json) with a mode of `"auto"` which takes priority over the [`package.json`](https://github.com/ImpactDevelopment/ImpactBot/blob/esm/package.json#L13) entry of `"strict"`.
