### ISSUE TITLE
Strict mode still affected by interop code in ".js" files

### ISSUE THREAD

**Issue by tilgovi** [standard-things/esm#456]
Repro: https://github.com/tilgovi/esm-strict-mode-error-repro

From the README there:

About
=====

With the `esm` "mode" set to `strict`, I found it surprising that the
code in `index.mjs` throws an exception when invoked as `node -r esm
index.mjs`.

Since `strict` mode should prevent reselect from being interpreted as
an ES module I was surprised to find the Babel ES module interop
boilerplate affects `esm`.

`import reselect from 'reselect'` errors.
`import * as reselect from 'reselect'` does not.

Removing the `__esModule` property from within `reselect` fixes the
error.

I expected that strict mode should prevent `esm` from interpreting the
`.js` file in `reselect` as an ES module, even with the `__esModule`
property on its exports.

**Comment by dnalborczyk** [comment]
I'm pretty sure it's just a bug and doesn't work as intended.

I believe `.mjs` files are always meant to mirror the node.js implementation, as far as I understand. `strict mode` shouldn't have any affect on the intended outcome. `mjs` is implicitly strict, e.g. cjs syntax in `.mjs` files is not allowed

I think the `strict mode` setting is meant as an indicator for esm to strictly mirror the node.js implementation and behavior for ES modules. e.g. with the esm default settings you can otherwise mix and match ES modules in `js` and `mjs` files.

**Comment by tilgovi** [comment]
@dnalborczyk that agrees with my expectations. I guess strict mode is not really relevant.

The surprise is only that `.mjs` modules import `.js` respecting `__esModule`. I understand that non-strict mode with `.js` importing `.js` there are interop options, but I did not think the interop would apply when performing the import from an `.mjs` file.

**Comment by jdalton** [comment]
@tilgovi Is correct. Inside an `.mjs` file there should be no `cjs.interop` support. I have a patch locally to resolve this. Now just working on a unit test.
