### ISSUE TITLE
Regression in v3.0.49 -- file is failing to unwrap default export

### ISSUE THREAD

**Issue by onlywei** [standard-things/esm#472]
Hello, I have made a reproducible test case in this repo here: https://github.com/onlywei/esm-bug-reproduction/tree/fail-to-unwrap

Please see the README in that repo for instructions on how to see the problem.

I have also tested in 3.0.51 and the issue still exists. My application is broken now ever since 3.0.49 and I have to downgrade.

**Comment by jdalton** [comment]
Hi @onlywei!

This is the result of a bug fix. So the new behavior is correct. Before we were allowing `.mjs` files to support loading pseudo ESM modules _(those with `__esModule`)_ but really `.mjs` should be locked down to not support `esm` options like `cjs.interop` and so should treat it as any other CJS file which is why it exports it as `{ default: module.exports }` which is why you get `default` value of `{ default: 'a string' }`
