### ISSUE TITLE
Issue upgrading to 3.0.57 - "Must use import to load ES module"

### ISSUE THREAD

**Issue by chadxz** [standard-things/esm#498]
Hello! My issue kind of walks the line between bug report and support request. Sorry if it is the latter, I can take to Stackoverflow if so.

I have been using esm with [chadxz/awry](https://github.com/chadxz/awry) and it's been working great for me. I use nyc and mocha for my tests, and have `--require esm` in my "mocha.opts" file. This configure has been working for me up to now.

After upgrading to `esm@3.0.57`, I am now getting the following message when I try to run my tests.

```
/Users/cmcelligott/src/awry/node_modules/mocha/lib/mocha.js:1
Error [ERR_REQUIRE_ESM]: Must use import to load ES module: file:///Users/cmcelligott/src/awry/test/api/ApplicationsAPI.spec.mjs
```

If i downgrade to `esm@3.0.56` it works fine. If I upgrade to anything past 3.0.56 it breaks.

Steps to reproduce:
1. `$ git clone https://github.com/chadxz/awry`
2. `$ npm i`
3. `$ mocha`

**Comment by jdalton** [comment]
Hi @chadxz!

This is intended. Earlier versions of `esm` had a bug that let `.mjs` files be sideloaded by mocha, nyc, and others. By Node rules `.mjs` files cannot be loaded with the builtin `require` function and should throw an `[ERR_REQUIRE_ESM]` error. Since `esm` locks down `.mjs` files and doesn't extend them any `esm` options they cannot be sidedloaded through todays tools.

The easy fix would be to switch from `.mjs` to `.js`. The `.js` extension has all `esm` defaults and support enabled. The other way would be to have your test entry script be a `.js` file that then loads the test `.mjs` file with a dynamic `import()`.

I added a note to the [tips](https://github.com/standard-things/esm#tips) section _(it is a little light though)_.

**Comment by chadxz** [comment]
Thank you! That got things going again. I opted to rename the files back to `.js` so I could continue to leverage mocha's test discovery mechanism.

**Comment by jdalton** [comment]
Okay! 

Ya, sorry about that 😅
The hardest thing for `esm` so far is keeping `.mjs` locked down _(so not "just work"ing)_.

**Comment by demurgos** [comment]
Thanks for the issue. I had the same issue today with Mocha and `esm` stopping to work with my `.mjs` files.

**Comment by jdalton** [comment]
My hunch is that most using `esm` do so for the interop enhancements with `.js` leaving `.mjs` use more limited. I was alerted to this gap by a happy user expressing their satisfaction of `.mjs` *"just working"* which was a red flag that I dropped detection somewhere.

@demurgos 

I think my doc note is a little light. If you or @chadxz have suggestions for a better warning I'm up for it.
The `.mjs` file extension should not be the thing developers reach for if they want interop or ease of use. It's available since it's in `--experimental-modules` but since it's not fully baked I can't commit to any enhancements to it.

**Comment by jdalton** [comment]
@demurgos 

> Now, I see that `require("./foo.mjs")` is not yet fully specified.

`esm` locks `.mjs` to the behavior defined in the current `--experimental-modules` implementation. That implementation does not allow `.mjs` files to be loaded with `require`.

There's several ways to address this. As mentioned above you can always have Mocha or other projects using `require` to load a `.js` file that loads the `.mjs` file through dynamic `import()`. You could use the `.js` extension with `esm`. Or you could use your fallback favorite transpiler/runtime to load the files.

**Comment by jdalton** [comment]
Just to be clear the restriction is on `.mjs` side loaded with `require`. This means while your test files can be `.js` (and support ESM by way of `esm`) your package files can still be `.mjs` and imported file within the `.js` test files using ESM syntax.

**Comment by jdalton** [comment]
You can see this by how `esm` uses Mocha to test its files [here](https://github.com/standard-things/esm/blob/master/test/tests.js).

**Comment by demurgos** [comment]
Thanks for the reply.
Having an entry file importing the `.mjs` files is a good idea (thanks for the example).
The downside is that I can't use Mocha's test file detection mechanism so I need to change the way I organize my tests but it's doable. It would also ensure that I use Node's native ESM which is a good thing.

I'll still try to recontact Mocha to land their PR adding support for `.mjs`, but at least I have your approach provides an alternative.
