### ISSUE TITLE
Getting `TypeError: Illegal invocation` error with esm@3.0.73

### ISSUE THREAD

**Issue by borisding** [standard-things/esm#541]
Hi!

I'm getting error from uuid package after upgrading to v3.0.73.

Repro link: https://github.com/borisding/repro-esm-uuid

OS: Windows 10
Node: v8.10.0
Error:
> `TypeError: Illegal invocation`

There is no issue with version v3.0.72

Thanks!

**Comment by jdalton** [comment]
Thanks @borisding!

I can reproduce this in Node 8, but not Node 10. It looks like a bug in our minified build.

**Comment by jdalton** [comment]
I regressed the minified build with this commit https://github.com/standard-things/esm/commit/aa358ae3ca4593323339db08727f2b33e27fb343 because it needs a side-effect as mentioned https://github.com/standard-things/esm/commit/6ab4d93b361a3a4edb66b33ab272ecd75c96c52b.

I'll add a code comment to not remove it again _(I keep wanting to simplify that check :blush:)_.

**Comment by jdalton** [comment]
**Update:**

[v3.0.74](https://github.com/standard-things/esm/releases/tag/3.0.74) is released 🎉

**Comment by jdalton** [comment]
@dnalborczyk If you pick this `needs tests` up a scenario test for the uuid package would cover it. Before publishing the tests are ran minified.
