### ISSUE TITLE
Koa server is not killed when using esm

### ISSUE THREAD

**Issue by remcohaszing** [standard-things/esm#552]
I’m running a Koa server using esm. However, when I end the process, the child processes remain running.

When I rewrite my code to cjs and remove esm, all child processes are killed with the top level process.

Is this a known issue / is there a known workaround?

**Comment by dnalborczyk** [comment]
thank you @remcohaszing 

I experienced the same issue, but I thought it was some wrong doing on my end. I changed some start scripts at the same time and didn't have time to look into it yet.

@remcohaszing if you don't need any fixes and additions from patch 73 and above, you can use `esm v3.0.72` for the time being till fixed.

@jdalton seems to be a regression. could be caused by: https://github.com/standard-things/esm/issues/530 and https://github.com/standard-things/esm/commit/b0938ce8ddc992c9bd9b83b80ca7366176454972

**Comment by davedoesdev** [comment]
I've noticed I have to ^C twice on fastify

**Comment by remcohaszing** [comment]
@dnalborczyk  Downgrading worked. Thanks!
