### ISSUE TITLE
Kind of confused on compatibility with actual esm (when they come to node)

### ISSUE THREAD

**Issue by zaynv** [standard-things/esm#56]
Hi, thanks for this awesome package. Sorry for opening an issue here for this question, but not sure where else to ask...

If I understand correctly this module provides multiple ways of specifying your modules (`package.json`, `'use module'`, `.mjs`, etc) but Node is only going to be bringing `.mjs` right? There won't be any `'use module'` pragma or anything? In this case, what's going to happen when esm does come to node and you want to switch from using `standard-things/esm` to native modules? Would you just change all your different options that you had before back to only using `.mjs`? Or is this something that people are going to be using even after esm comes out so that you don't have to use `.mjs`? Thank you.

**Comment by jdalton** [comment]
Hi @zaynv!

By default`@std/esm` tries to follow the [Node way](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md) as close as possible.

You can [unlock](https://github.com/standard-things/esm#unlockables) non-standard and custom features at your discretion 

>  Or is this something that people are going to be using even after esm comes out so that you don't have to use `.mjs`?

I'm sure many will choose to continue to use `@std/esm` for quite a while after built-in support lands because they'll have older Node versions to support. Even after older Node versions aren't a concern others will stay with `@std/esm` due to their file extension or CJS compatibility preferences.
