### ISSUE TITLE
`main` field is always preferred over `module`

### ISSUE THREAD

**Issue by pi0** [standard-things/esm#627]
### Description

`main.js`:

```js
require('esm')(module, {
 mainFields: [
    'module',
    'main'
 ]
})('.')
```

`package.json`:

```json
{
    "main": "index.js",
    "module": "index.mjs"
}
```

Expected behaviour: `index.mjs` being loaded when running `node main`.

Current behaviour: `index.js` will be loaded if exists.

### Info

- ESM version: `3.0.84`
- Reproduction repo: https://github.com/pi0/esm-module-field-bug

### The story

With nuxt/nuxt.js#4051 we are going to make Nuxt fully ESM compatible. For faster startup time, production builds use rollup dist files (`main` field) but during development/test we don't want a build step! So if the package is being loaded through ESM it is expected that `module` field to be preferred. [This](https://github.com/nuxt/nuxt.js/blob/feat/packages/scripts/nuxt) is the dev-only script that I've prepared for this purpose. But it is not working.

**Comment by jdalton** [comment]
Hi @pi0!

This is by design. The `.mjs` file extension is locked down to not support any of the `esm` options, including the `mainFields`. The `esm` loader can also let you ship just ESM source without the need for a hybrid bundle. You can set your `module` field to `main.js` _(or whatever the real ESM entry is)_ and let the `main` field use `index.js` as the CJS bridge. I'll give my Node core + Module WG spiel below:

>:wave: Node core and Node Module WG member here. There is no set date for when `--experimental-modules` will be unflagged. There's also no guarantee that what has shipped now is what will be in the future. For example, there are several discussions in the Node Module WG on how to approach implementation. One such discussion is to ship a maximally minimal implementation that would require package-name-maps for resolving bare specifiers _(no longer using the Node module resolution algorithm)_. 
>
>Adopting `.mjs` with the idea that its current support is solid _(for production use)_ at this stage is bit premature and may cause headaches for users. I've already seen `.mjs` cause issues for real projects like react-apollo, graphql, and create-react-app due to complications with babel, webpack, testing/mocks, or dual packages Also, if/when changes do happen to Node's `--experimental-modules` your ESM story could be various shades of broken.
>
>The `--experimental-modules` flag really does mean experimental. It's something you should pause and consider at least before going all in as the route for your ESM support strategy today.

Please let me know if I can pitch in with package design guidance or any other assistance. You'll find sticking with `.js` for ESM code will not only make working with `esm` easier, but it should also make working with Babel and Webpack easier too.
