### ISSUE TITLE
Stop using Node's internal APIs

### ISSUE THREAD

**Issue by vkurchatkin** [standard-things/esm#66]
Currently `esm` uses the following APIs:

- `new Module`
- `Module.wrap`
- `Module._compile`
- ` Module._extensions`
- `Module._resolveFilename`
- `Module._cache`
- `Module._nodeModulePaths`
- `path._makeLong`
- `process.binding`
  - `fs`
    - `getStatValues`
    - `stat`
    - `internalModuleReadFile`
    - `internalModuleStat`
  - `natives`
  - `util`
    - `arrow_message_private_symbol`
    - `decorated_private_symbol`
    - `decorateErrorStack`
    - `setHiddenValue`
- `process._tickCallback`
- `process._preload_modules`
- `REPLServer.prototype.createContext`

This APIs are considered internal (or private) and shouldn't be used. Their behaviour can be changed or they can disappear at any time, even in patch release, thus breaking `esm` and all of its dependants.

**Comment by jdalton** [comment]
Thanks @vkurchatkin!

Our usage of pseudo internals falls into a few buckets.

* Required for as a hook for the common module loader, REPL, or run main scenario
  * Common Loader
    - `new Module`
    - `Module.wrap`
    - `Module._cache`
    - `Module._compile`
    - ` Module._extensions`
    - `Module._nodeModulePaths`
    - `Module._resolveFilename`

  * REPL
    - `process._preload_modules`
    - `REPLServer.prototype.createContext`

  * Run main
    - `process._preload_modules`
    - `process._tickCallback`

These are used to either enable the hook or recreate behavior of various code paths.
The hooks for each scenario *(common loader, REPL, run main)* are only enabled for the given scenario and not all at one.

* Bonus for optimized operations
  - `path._makeLong`
  - `process.binding`
      - `fs`
        - `getStatValues`
        - `internalModuleReadFile`
        - `internalModuleStat`
        - `stat`
      - `natives`
      - `util`
        - `arrow_message_private_symbol`
        - `decorated_private_symbol`
        - `decorateErrorStack`
        - `setHiddenValue`

When possible operations are guarded to prevent failure. This is especially true for operations for functionality that either enhances debugging or performance is considered bonus. As such we guard its usage with fallbacks and catches.

While it's true some pseudo APIs can and do change the one's we're using for hooks are a bit more resilient. They have existed for many years and Node versions. Because so many packages rely on their existence and behavior they are essentially frozen. In addition, to help solidify cow paths I plan to have Lodash take a dependency on `@std/esm`, leveraging its CITGM release gate status to avoid preventable breaks.

Having access to pseudo internals enables some pretty incredible things, but understandably increases the compat and support burden of Node core. This is why while Node's CJS is a bit of the wild west, Node's ESM support is being planned in such a way to restrict these bits. 

I'm only closing the issue as `invalid` since you've offered nothing actionable.
If you have ways to avoid some of them that would be great.

**Comment by MylesBorins** [comment]
@jdalton would you be willing to reopen this issue so we can use it as a place to discuss what kind of APIs you might be able to use to avoid relying on internals?

**Comment by jdalton** [comment]
Done!

**Comment by refack** [comment]
First I said it before, and I'll say it again. IMHO this is a valuable module, that solves the real problem of migrating modules to ESM.
I'd be happy if node core would find a way to incorporate/recommend/sanctify it as the way to do ESM in existing version of node.

> In addition, to help solidify cow paths I plan to have Lodash take a dependency on @std/esm, in part leveraging its CITGM release gate status to avoid preventable breaks. (or at least get the heads up on them)

I think that until there is full buy-in from node core, the cons of introducing it to `lodash` outway the pros. As was commented in https://github.com/nodejs/CTC/issues/164#issuecomment-323611827 changing the global behaviour of node (even with supported APIs) should be left to the end user. IMHO Introducing it in a deep dependency like `lodash` will lead to fragility.

There is an interesting idea in https://github.com/nodejs/node/pull/12349 about implementing a hook for transforming module during `require`, maybe we can work off that.

**Comment by jdalton** [comment]
> First I said it before, and I'll say it again. IMHO this is a valuable module, that solves the real problem of migrating modules to ESM.
I'd be happy if node core would find a way to incorporate/recommend/sanctify it as the way to do ESM in existing version of node.

🙌 

> I think that until there is full buy-in from node core, the cons of introducing it to lodash outway the pros.

Having buy-in from node core would rock. If the situation doesn't improve and Node core is still super concerned when the time for Lodash v5 comes closer I could always offer it as a package flavor (like [lodash-es](https://www.npmjs.com/package/lodash-es) for folks that are up for it).

> There is an interesting idea in nodejs/node#12349 about implementing a hook for transforming modules during require, maybe we can work off that.

Neat. I'll give it a look for sure!

**Comment by jdalton** [comment]
> As was commented in nodejs/CTC#164 (comment) changing the global behaviour of node (even with supported APIs) should be left to the end user.

The `@std/esm` loader isn't a global hammer. Only packages that opt-in to it by having it as a dependency, dev dependency, peer dependency, or options config get the loader. For everyone else they get the default built-in behavior. So package A (which doesn't use `std/esm`) can depend on package B (that does use `std/esm`) and  package A will continue to load as normal without the ESM hooks being applied to it.

**Comment by jdalton** [comment]
The `@std/esm` loader also supports versioning so package B can use version 1 of `@std/esm` and depend on package C that uses version 2 of `@std/esm` and both work together without stepping on each others toes.

**Comment by mcollina** [comment]
> If the situation doesn't improve and Node core is still super concerned when the time for Lodash v5 comes closer I could always offer it as a package flavor (like lodash-es) for folks that are up for it.

I think having it as a flavor would be awesome for everyone. However, let's do our best to lift the doubts.

> The @std/esm loader isn't a global hammer. Only packages that opt-in to it by having it as a dependency, dev dependency, peer dependency, or options config get the loader. For everyone else they get the default built-in behavior. So package A (which doesn't use std/esm) can depend on package B (that does use std/esm) and package A will continue to load as normal without the ESM hooks being applied to it.

@jdalton I briefly looked for this information in the README, and there is no doc for it. Can you please explain how the hooks encapsulation is achieved? I am really worried about this becoming a global hammer.

I would be extremely less worried if the API would be:

```js
module.exports = require("@std/esm")("./main.mjs").default
```

which would not require monkey patching core internals (if I understand correctly how all of this work). In this way all of that is loaded in sub-tree started from the above file will use `require("@std/esm")`, but everything else will be left untouched.

The preloader should stay it is as it is a great feature for applications.

**Comment by jdalton** [comment]
>  I briefly looked for this information in the README, and there is no doc for it. Can you please explain how the hooks encapsulation is achieved? I am really worried about this becoming a global hammer.

The main hook wraps `Module._extensions` of `".js", ".gz", ".js.gz", ".mjs.gz", ".mjs"` and then defers to previous handler, if the file hasn't opt-ed in*, or goes down the ESM route if it has:
https://github.com/standard-things/esm/blob/master/src/hook/compile.js#L34-L44

I believe your idea of `require("@std/esm")("./main.mjs").default` would work. It avoids the need to hook `Module._extensions` in the first place since I code transform calls I control what the `require` or `import` translate into and already have my own handlers. This could also simplify versioning too! I'll work on patching that today!

**Comment by mcollina** [comment]
> I believe your idea of require("@std/esm")("./main.mjs").default would work. It avoids the need to hook Module._extensions in the first place since I code transform calls I control what the require or import translate into and already have my own handlers. This could also simplify versioning too! I'll work on patching that today!

It also reduces the number of internal hooks that we need to expose in core.

**Comment by jdalton** [comment]
I'm pretty excited about it!

**Comment by jdalton** [comment]
\cc @hzoo @benjamn

This might be something for `babel-register` and `reify` instead of using extension hooks you could do:
```js
require("babel-register")("./main.mjs")
require("reify")("./main.mjs").default
```

**Comment by jdalton** [comment]
Ok so it looks like using @mcollina's approach should be a winner. To reduce the number of pseudo internals used I'm simply going to copy their source code over as individual modules (since they're written in JS).

This means there will be essentially no pseudo internal usage for the primary module use beyond some remaining for [guarded bonus functionality](https://github.com/standard-things/esm/issues/66#issuecomment-323590058) and potentially checking `Module._cache`. 

The methods I can copy over include:
  - `new Module`
  - `Module.wrap`
  - `Module._cache`
  - `Module._compile`
  - `Module._extensions`
  - `Module._nodeModulePaths`
  - `Module._resolveFilename`
  - `path._makeLong`
  - `process.binding("natives")`

Reference I can guard or are already guarded
    - `process._preload_modules` *(guarded)*
    - `process._tickCallback` **(need to guard)**
    - `process.binding("fs")  *(guarded)*
    - `process.binding("util")  *(guarded)*

Leaving just unguarded (only used in the REPL case)
  - `REPLServer.prototype.createContext`
  
As for the `node -r` and REPL cases their usage can be guarded. But as they are supplemental functionality, touch very few pseudo internals, and are not critical to general use I'm ok taking the support burden for them.

With this there's no longer a hook into the primary module loading mechanism and significantly reduced pseudo internals.

I'll update the thread with commit references as they come.
These changes will land before the next release.

**Comment by benjamn** [comment]
🤔  Interesting idea! Meteor doesn't use any `require.extensions`-style hooks at runtime (we precompile everything), but it's super tempting to create a system where we control the implementation of `require` for certain modules, rather than changing how `require` works for all Node code.

**Comment by jdalton** [comment]
> but it's super tempting to create a system where we control the implementation of `require` for certain modules

Ya `@std/esm` does it to enforce Node's ESM rules around loading `.mjs` with `require`.
Super handy!

**Comment by jdalton** [comment]
On a serious note, while [everything worked out in the end](https://github.com/nodejs/CTC/issues/164#issuecomment-323639516), I'm not happy about how https://github.com/nodejs/CTC/issues/164 was handled by Node core.

I'm pretty fortunate. I...

* work at Microsoft, which is a platinum member of the Node foundation
* have TC39 representation through Microsoft and the JS Foundation
* have worked with the CTC on past proposals
* run the most directly depended upon npm package
* have allies in the Node community to run interference

And I was treated like garbage. I absolutely dread dealing with Node folks.
I walk on egg shells around them. It's super intimidating. I can [only imagine how others feel](https://github.com/nodejs/community-committee/issues/111).

I'm locking the thread because I don't want a fuss.
I'll update the thread with commit references as they come.
