### ISSUE TITLE
Mocha + ts-node + esm = 😢

### ISSUE THREAD

**Issue by stevefan1999-personal** [standard-things/esm#680]
https://github.com/stevefan1999-personal/mocha-tsnode-esm-regress

After installing:
```
⟩ pnpm test

> @ test /Projects/~snip~/mocha-tsnode-esm-regress
> mocha --opts .config/mocha.opts

file:///Projects/~snip~/mocha-tsnode-esm-regress/packages/index.test.ts:5
function doWork(): Promise<void> {
                 ^

SyntaxError: Invalid or unexpected token
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
npm ERR! Test failed.  See above for more details.
```
Possibly a regression of https://github.com/standard-things/esm/issues/568

**Comment by stevefan1999-personal** [comment]
Nevermind, I have made hacks on the reproduction repo and it should be the best workaround .

**Comment by jdalton** [comment]
Hi @stevefan1999-personal!

Do you know if this is a legit regression _(did it work in a previous version of `esm`)_.
Or if this is a new scenario to cover? I do this this issue looks like a different scenario than #568, and the scenario opened here is now different once again with your change (it now includes code coverage). I started to dig in but will hold off since it's a moving target. If you clearly explain your issue and what you're trying to do that might help.

**Comment by jdalton** [comment]
Ah nice! Do you have links to the relevant mocha thread/comment handy?

**Comment by stevefan1999-personal** [comment]
@jdalton sadly, no, I roamed a while and couldn't find it.
