### ISSUE TITLE
Is there a way to control the global object?

### ISSUE THREAD

**Issue by justinfagnani** [standard-things/esm#682]
I'm trying to use esm from within jsdom and while it works enough to load a module, the globals that jsdom defines on window are not present. Is there a way to get esm to use the global object from the context in which it's invoked?

The code I'm trying is something like this:
```js
    const jsdom = new JSDOM(`<!doctype html>`, {
      runScripts: 'outside-only',
    });
    jsdom.window.require = require;
    jsdom.window.module = module;
    const s = new Script(`
      require = require('esm')(module);
      require('my-web-module');
    `);
    jsdom.runVMScript(s);
    console.log(jsdom.window.document.body.innerHTML);
```

**Comment by jdalton** [comment]
Hi @justinfagnani!

Would you create a small repo for me to check out your scenario.

**Comment by justinfagnani** [comment]
Hey 👋

The code above is almost exactly it. I made a gist with the module I'm trying to load too: https://gist.github.com/justinfagnani/6d0f7e904c43a5ed2a213fa8e0e75f6a

**Comment by jdalton** [comment]
Ah okay!

If you were to replace the two lines of requiring `esm` and loading `my-test-module` with 
```js
require("./check-window")
```
With `check-window.js` being
```js
console.log(window)
```
and run that it will produce
```
/Users/jdalton/projects/demo/check-window.js:1
(function (exports, require, module, __filename, __dirname) { console.log(window)
                                                                          ^
ReferenceError: window is not defined
```
This is because the `vm` instance the `jsdom` script is running in is different than the one the injected `require` is running in.

In the short-term you can workaround this by doing
```js
const global = require("vm").runInThisContext("global")
global.window = window
```
Before loading `my-test-module`.

In the long-term I can look into adding a `global` option to tackle some of that.

**Comment by justinfagnani** [comment]
@jdalton any thoughts here since it sounded like you were doing some major work for the next version?

**Comment by StreetStrider** [comment]
@jdalton I got custom global console instance in my project and when I activate esm, it seemes shadowed by other instance. I presume, esm somehow injects its own console instance right after me doing the same with my custom console. When I use another name (like `console2`) issue disappears.

Can you give some tips how to get my own console visible globally across modules?

**Comment by StreetStrider** [comment]
Looks similar to this #622

**Comment by jdalton** [comment]
@StreetStrider 
> Can you give some tips how to get my own console visible globally across modules?

If you can provide a simple repro repo that would help me diagnose an issue or prescribe usage.

**Comment by StreetStrider** [comment]
@jdalton I've put repro here. Sorry for custom dep, the issue is reproduced in callback of it.
https://github.com/StreetStrider/esm-console ([zip](https://github.com/standard-things/esm/files/2889943/esm-console-master.zip)).

Also found this:
![default](https://user-images.githubusercontent.com/2124761/53181085-eec3ef80-3607-11e9-860d-0f444d22fbd2.png)
however this might be just an esm's implementation detail.

**Comment by jdalton** [comment]
Thanks for the repro @StreetStrider! I found the issue and should have a patch/fix in a day or so (traveling so there's gonna be a slight delay).

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/77ec69dc340a88d45719ecace885db28248fb7ca

**Comment by StreetStrider** [comment]
@jdalton thank you, will try `master` till release.

**Comment by StreetStrider** [comment]
@jdalton, fyi, when I install from `"esm": "github:standard-things/esm"` I got
`Error: Cannot find module 'execa'` on prepare step.

It looks like a possible error or maybe just master is not intended to be installable.

**Comment by jdalton** [comment]
[v3.2.6](https://github.com/standard-things/esm/releases/tag/3.2.6) is released 🎉

**Comment by StreetStrider** [comment]
@jdalton works as expected now in all recently flawed scenarios. :+1:
