### ISSUE TITLE
Why removing gzip module support?

### ISSUE THREAD

**Issue by sodatea** [standard-things/esm#686]
Hi I just came across an old podcast about @std/esm and it says this loader supported gzip modules which significantly reduces the lodash package size. But when I read the code on GitHub, I see the support was dropped without an explicit reason (https://github.com/standard-things/esm/commit/61e10a42c5c2dcfe3e6ecdc1f6cc4565f1cecbdc). Are there any concerns on this feature?

**Comment by jdalton** [comment]
Hi @sodatea!

I made the call to remove it because it added a lot of complexity to our implementation at the time. You can see by the changeset that it touched a lot of things. So in an effort to simplify things I removed it. Other than that I'd still dig seeing gzip modules or even brotli'ed (there's an open PR to add native brotli support to Node) modules become more of a thing.
