### ISSUE TITLE
Behavior change from 3.1.4 to 3.2.0 aka. breaking change

### ISSUE THREAD

**Issue by dkundel** [standard-things/esm#720]
Hey there!

We experienced a breaking change with the recent update in `esm`. You can see the error referenced here: https://github.com/twilio/flex-plugin-builder/issues/37

Pinning the version to `3.1.4` seems to temporarily fix it. You can find the source code that is using `esm` here: https://github.com/twilio/flex-plugin-builder/blob/master/packages/create-flex-plugin/bin/create-flex-plugin

I suppose this change of behavior should have probably been a major change but could you inform us how to properly fix this to not encounter an issue like this again?

Cheers,
Dominik

**Comment by jdalton** [comment]
Hi @dkundel!

Thanks! Yes, I was testing the waters to see if I did a minor bump if I would get breaking reports. Since we stayed so long at `3.0.x` (84 releases) I suspected many would have started pinning to the patch number or used the `~` range. Sorry for the inconvenience. Going forward I'll keep these kinds of changes to major bumps.

The change was that with `options.cjs.interop`, enabled by default, we now return the `default` export in cases where you only export a `default`. This helps folks migrating individual modules to ESM within their project because their existing CJS that looks like `require("./mod")` WOULD NOT need to be rewritten as `require("./mod").default`.

The case of 
```js
require = require('esm')(module /*, options*/);
require('../src/cli.js')
```
is interesting, since it's a bridge, folks could get the full export and manually pluck the `.default` (as you're already doing). Opinions?

To resolve this you could change your snippet to:
```js
require('../src/cli.js')()
  .parse(process.argv.slice(2));
```

**Comment by dkundel** [comment]
I personally think even though the `.default()` looks odd, it's a useful educational factor to write more ESM compatible CJS code. However, I'm not too attached to it. 

It largely caused an incident with customers for us, because we haven't had pinned it to a patch version but instead relied on the default version pinning of npm for this one. 

So I just want to make sure that we are protected for the future. Other debates that sparked up through this was to move to a bundling approach and run tests against it so that at least during installation there is no surprise.

**Comment by jdalton** [comment]
> I personally think even though the .default() looks odd, it's a useful educational factor to write more ESM compatible CJS code. However, I'm not too attached to it.

Thank you for the feedback! 
#### .esmrc
```json
{
  "cjs": {
    "interop": false
  }
}
```
With the config above 👆 you can disable `cjs.interop` and preserve the `.default()` behavior.

> It largely caused an incident with customers for us, because we haven't had pinned it to a patch version but instead relied on the default version pinning of npm for this one.

Yikes! 😳

> So I just want to make sure that we are protected for the future.

For `esm` I'll try, though I can't speak for your other dependencies and I can't guarantee that regressions won't happen. Pinning may not be a bad idea in general.

**Comment by jdalton** [comment]
**Update**:

After other reports I'm reverting the auto dedefaulting behavior in the next bump.
